"""Added courseVideo

Revision ID: 968bcdc6c8f6
Revises: c7b07b05ca96
Create Date: 2025-03-30 18:48:00.641319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '968bcdc6c8f6'
down_revision: Union[str, None] = 'c7b07b05ca96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('video', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'video')
    # ### end Alembic commands ###
