"""Added userBlocks

Revision ID: a2589e469e3d
Revises: f907b81309a6
Create Date: 2025-04-06 22:31:39.467308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2589e469e3d'
down_revision: Union[str, None] = 'f907b81309a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_blocks', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_blocks', 'blocks', ['block_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_blocks', type_='foreignkey')
    op.drop_constraint(None, 'user_blocks', type_='foreignkey')
    # ### end Alembic commands ###
